repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.9
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: local
  hooks:
    - id: ty-check
      name: type check
      language: system
      always_run: true
      entry: ty check
      pass_filenames: false
