"""User fields.

Revision ID: 846ca2dce93c
Revises: 3a3bd7abb6da
Create Date: 2025-08-16 02:06:20.937616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "846ca2dce93c"
down_revision: Union[str, Sequence[str], None] = "3a3bd7abb6da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(length=255), nullable=False))
    op.add_column("users", sa.Column("status", sa.String(length=255), nullable=False))
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "status")
    op.drop_column("users", "password")
    # ### end Alembic commands ###
